### ISSUE TITLE
Citation or reference to data if used

### ISSUE THREAD

**Issue by dignatiuk** [SIOS-Svalbard/SDMSInteroperabilityGuidelines#3]
Add to the Data Access Point requirements about data citation (references) from SIOS Data Policy.
Add for the datasets the references to the data policies from the contributing centres. Especially for data, that you can download in DAP.

**Comment by steingod** [comment]
The only thing we can add is a general statement in the data portal about citation of data. Else licenses should follow all datasets: I have added a more specific recommendation on this in the IOG and also a statement to the DAP.
