### ISSUE TITLE
Metadata Name is marked as unique

### ISSUE THREAD

**Issue by filchos** [SIOS-Svalbard/SDMSInteroperabilityGuidelines#5]
In [Table 2 of the technical documentation](https://htmlpreview.github.io/?https://github.com/SIOS-Svalbard/SDMSInteroperabilityGuidelines/blob/master/doc/sdms_iog.html#gcmd-dif-elements) the elements  `Metadata_Name` and `Metadata_Version` are marked as unique in 3 of 4 cases.

**Comment by steingod** [comment]
This table is no longer in the document, closing issue.
